package net.phoenixvine.domains.config;

import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.fml.event.config.ModConfigEvent;
import net.minecraftforge.fml.loading.FMLPaths;
import net.phoenixvine.domains.PhoenixDomains;

import com.electronwill.nightconfig.core.CommentedConfig;
import com.electronwill.nightconfig.core.UnmodifiableConfig;
import com.electronwill.nightconfig.core.file.CommentedFileConfig;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Applies a global, pack-distributable override layer on top of {@link DomainsConfig}'s
 * per-world {@code serverconfig/phoenix_domains-server.toml}.
 *
 * <p>
 * Modpack developers cannot ship into {@code saves/<world>/serverconfig/} because that
 * path doesn't exist until a world is created, and Forge regenerates that file fresh (with
 * defaults) the first time each world loads. What they CAN ship is the pack's own global
 * {@code config/} folder. So this reads an optional
 * {@code config/phoenix_domains-server-overrides.toml} — same key layout as the per-world
 * file, just with {@code -overrides} inserted before the extension — and re-applies its
 * values every time {@link DomainsConfig#SPEC} loads or reloads, regardless of what the
 * per-world file itself contains.
 *
 * <h2>The file is auto-generated, at defaults, on first load</h2>
 * If {@code config/phoenix_domains-server-overrides.toml} doesn't exist yet, it's generated on
 * the spot (same {@code ModConfigEvent.Loading}/{@code Reloading} hook) with every overridable
 * key present and set to its current shipped default — nested tables and all, same layout as a
 * generated per-world file — plus a header comment explaining what it is. A pack dev can then
 * open it and edit only the keys they actually want to pin; everything else stays a harmless,
 * self-documenting record of "this is what a stock install looks like right now."
 *
 * <p>
 * Because of that, "key is present in the file" can no longer mean "this is an active
 * override" — every key is always present. Instead, {@link #applyLeaf} only treats a key as an
 * active override if its value in the file differs from that key's own {@code ConfigValue}
 * {@link ForgeConfigSpec.ConfigValue#getDefault() getDefault()} (the spec's own default, not
 * anything per-world). This also keeps the mechanism forward-compatible: if a pack's overrides
 * file was generated by an older version of this mod and this mod's default for some key later
 * changes, an untouched entry in the file (still equal to the OLD default) is silently treated
 * as "not an override" rather than freezing that field at a now-stale value forever.
 *
 * <h2>Why this can't just mutate the backing config data</h2>
 * The obvious approach — grab {@code event.getConfig().getConfigData()} (the live
 * {@link CommentedConfig} NightConfig bound to {@link DomainsConfig#SPEC}) and call
 * {@code .set(path, value)} on it directly, or equivalently call {@code .set(value)} on the
 * specific {@link ForgeConfigSpec.ConfigValue} field — was verified (by reading Forge
 * 1.20.1-47.4.0's own sources, {@code ConfigTracker.openConfig} and
 * {@code ForgeConfigSpec.ConfigValue#set}) to be unsafe for this use case:
 * <ul>
 * <li>{@code ConfigTracker.openConfig(...)} does, in order: bind the freshly-read
 * per-world file as the config's backing data (this also resets every
 * {@code ConfigValue}'s cache), fire {@code ModConfigEvent.Loading} to mod-bus listeners
 * (this is where our listener runs), then unconditionally call {@code config.save()}.</li>
 * <li>{@code ConfigFileTypeHandler.reader(...)} builds that backing
 * {@link CommentedFileConfig} with {@code .autosave()}, so NightConfig persists to disk
 * on every mutating call, not just on the explicit {@code save()} above.</li>
 * <li>{@code ForgeConfigSpec.ConfigValue#set(T)} itself does
 * {@code spec.childConfig.set(path, value); this.cachedValue = value;} — i.e. it writes
 * through to the exact same backing object as the raw-path approach. There is no
 * Forge-public way to update a {@code ConfigValue}'s live value that doesn't also write
 * through to the backing (and hence per-world-file-backed, autosaving) config.</li>
 * </ul>
 * Either approach would therefore silently bake every override permanently into each
 * world's own {@code serverconfig/phoenix_domains-server.toml} the moment that world loads —
 * exactly what the "never touch the per-world file" requirement forbids, and a much worse
 * outcome than doing nothing (it would survive the override file being removed later).
 *
 * <h2>What we do instead</h2>
 * {@link ForgeConfigSpec.ConfigValue#get()} only re-reads from the backing config when its
 * private {@code cachedValue} field is {@code null}; otherwise it just returns the cached
 * object. Forge's own cache-reset (triggered by binding the per-world file) always happens
 * <em>before</em> {@code ModConfigEvent.Loading}/{@code Reloading} is fired to mod-bus
 * listeners, and nothing clears the cache again afterward until the next load/reload. So we
 * reflectively write the override value directly into that private {@code cachedValue}
 * field, bypassing {@code childConfig} entirely. Subsequent {@code .get()} calls return our
 * override, and because we never touched {@code childConfig}, Forge's own trailing
 * {@code config.save()} just re-serializes exactly what it already had — the per-world file
 * is left untouched by us.
 */
public final class DomainsConfigOverrides {

    private static final Logger LOGGER = LogManager.getLogger();
    private static final String OVERRIDE_FILE_NAME = "phoenix_domains-server-overrides.toml";

    private static Field cachedValueField;

    private DomainsConfigOverrides() {}

    public static void onLoad(ModConfigEvent event) {
        if (event.getConfig().getSpec() != DomainsConfig.SPEC) {
            return;
        }

        Path overridePath = FMLPaths.CONFIGDIR.get().resolve(OVERRIDE_FILE_NAME);
        if (!Files.exists(overridePath)) {
            try {
                generateDefaultOverrideFile(overridePath);
            } catch (Exception e) {
                LOGGER.warn("[{}] Unexpected error auto-generating global config override file '{}' — " +
                        "continuing without one. Cause: {}", PhoenixDomains.MOD_ID, OVERRIDE_FILE_NAME, e.toString());
            }
            if (!Files.exists(overridePath)) {
                // Generation failed (already logged) — nothing to load this pass.
                return;
            }
        }

        CommentedFileConfig overrideConfig = CommentedFileConfig.builder(overridePath).sync().build();
        try {
            overrideConfig.load();
        } catch (Exception e) {
            LOGGER.warn("[{}] Failed to parse global config override file '{}' — ignoring it. Cause: {}",
                    PhoenixDomains.MOD_ID, OVERRIDE_FILE_NAME, e.toString());
            return;
        }

        try {
            Map<String, ForgeConfigSpec.ConfigValue<?>> valuesByPath = collectConfigValues();
            applyOverrides(overrideConfig, new ArrayDeque<>(), valuesByPath);
        } catch (Exception e) {
            LOGGER.warn("[{}] Unexpected error applying global config overrides from '{}' — some or all " +
                    "overrides may not have been applied. Cause: {}", PhoenixDomains.MOD_ID, OVERRIDE_FILE_NAME,
                    e.toString());
        } finally {
            overrideConfig.close();
        }
    }

    private static void applyOverrides(UnmodifiableConfig node, Deque<String> pathSoFar,
                                       Map<String, ForgeConfigSpec.ConfigValue<?>> valuesByPath) {
        for (Map.Entry<String, Object> entry : node.valueMap().entrySet()) {
            Object rawValue = entry.getValue();
            pathSoFar.addLast(entry.getKey());
            try {
                if (rawValue instanceof UnmodifiableConfig nested) {
                    applyOverrides(nested, pathSoFar, valuesByPath);
                } else {
                    String dottedPath = String.join(".", pathSoFar);
                    applyLeaf(dottedPath, rawValue, valuesByPath);
                }
            } finally {
                pathSoFar.removeLast();
            }
        }
    }

    private static void applyLeaf(String dottedPath, Object rawValue,
                                  Map<String, ForgeConfigSpec.ConfigValue<?>> valuesByPath) {
        ForgeConfigSpec.ConfigValue<?> configValue = valuesByPath.get(dottedPath);
        if (configValue == null) {
            LOGGER.warn("[{}] '{}' has override key '{}' which does not match any known {} config path — " +
                    "ignoring it (check for a typo).", PhoenixDomains.MOD_ID, OVERRIDE_FILE_NAME, dottedPath,
                    PhoenixDomains.MOD_ID);
            return;
        }

        Object defaultValue = configValue.getDefault();
        Object coerced;
        try {
            coerced = coerce(rawValue, defaultValue);
        } catch (Exception e) {
            LOGGER.warn("[{}] Override key '{}' in '{}' has a value of the wrong type ({}) — ignoring it.",
                    PhoenixDomains.MOD_ID, dottedPath, OVERRIDE_FILE_NAME, rawValue, e);
            return;
        }

        if (Objects.equals(coerced, defaultValue)) {
            // The generated file ships every key at its current default, so "present in the
            // file" no longer implies "meant as an override". Only a value that's been edited
            // away from this key's own (current) default counts as an active override — this
            // also means an entry left over from an older mod version, whose default has since
            // changed, is quietly ignored here rather than permanently freezing the field.
            return;
        }

        try {
            setCachedValue(configValue, coerced);
            LOGGER.info("[{}] Applied global config override: {} = {}", PhoenixDomains.MOD_ID, dottedPath, coerced);
        } catch (ReflectiveOperationException e) {
            LOGGER.warn("[{}] Failed to apply global config override for '{}' due to a reflection error: {}",
                    PhoenixDomains.MOD_ID, dottedPath, e.toString());
        }
    }

    /** Coerces a NightConfig-parsed TOML value to match the declared config value's runtime type. */
    private static Object coerce(Object rawValue, Object defaultValue) {
        if (defaultValue instanceof Integer && rawValue instanceof Number n) {
            return n.intValue();
        }
        if (defaultValue instanceof Long && rawValue instanceof Number n) {
            return n.longValue();
        }
        if (defaultValue instanceof Double && rawValue instanceof Number n) {
            return n.doubleValue();
        }
        if (defaultValue instanceof Float && rawValue instanceof Number n) {
            return n.floatValue();
        }
        if (defaultValue instanceof Boolean && rawValue instanceof Boolean) {
            return rawValue;
        }
        if (defaultValue instanceof String && rawValue instanceof String) {
            return rawValue;
        }
        if (defaultValue instanceof Enum<?> && rawValue instanceof String s) {
            @SuppressWarnings({ "unchecked", "rawtypes" })
            Enum<?> matched = Enum.valueOf((Class<? extends Enum>) defaultValue.getClass(),
                    s.toUpperCase(java.util.Locale.ROOT));
            return matched;
        }
        if (defaultValue != null && defaultValue.getClass().isInstance(rawValue)) {
            return rawValue;
        }
        throw new IllegalArgumentException("cannot coerce " + rawValue + " (" +
                (rawValue == null ? "null" : rawValue.getClass()) + ") to " +
                (defaultValue == null ? "null" : defaultValue.getClass()));
    }

    private static void setCachedValue(ForgeConfigSpec.ConfigValue<?> configValue, Object value)
                                                                                                 throws ReflectiveOperationException {
        if (cachedValueField == null) {
            Field field = ForgeConfigSpec.ConfigValue.class.getDeclaredField("cachedValue");
            field.setAccessible(true);
            cachedValueField = field;
        }
        cachedValueField.set(configValue, value);
    }

    /**
     * Writes a fresh {@code config/phoenix_domains-server-overrides.toml} populated with every
     * overridable key at its current default (nested tables matching the per-world file's own
     * layout, with each key's Forge-defined comment carried over where available), plus a
     * header comment explaining that editing a value here is what turns it into an active
     * override. Never touches an already-existing file — only called when one is missing.
     */
    private static void generateDefaultOverrideFile(Path overridePath) {
        if (overridePath.getParent() != null) {
            try {
                Files.createDirectories(overridePath.getParent());
            } catch (Exception e) {
                LOGGER.warn("[{}] Failed to create the config directory for '{}' — skipping " +
                        "auto-generation of the global override file. Cause: {}", PhoenixDomains.MOD_ID,
                        OVERRIDE_FILE_NAME, e.toString());
                return;
            }
        }

        CommentedFileConfig fileConfig = CommentedFileConfig.builder(overridePath).sync().build();
        try {
            UnmodifiableConfig specTree = DomainsConfig.SPEC.getSpec();
            Map<String, ForgeConfigSpec.ConfigValue<?>> valuesByPath = collectConfigValues();
            for (ForgeConfigSpec.ConfigValue<?> configValue : valuesByPath.values()) {
                List<String> path = configValue.getPath();
                fileConfig.set(path, configValue.getDefault());

                Object specNode = specTree.get(path);
                if (specNode instanceof ForgeConfigSpec.ValueSpec valueSpec && valueSpec.getComment() != null) {
                    fileConfig.setComment(path, valueSpec.getComment());
                }
            }
            fileConfig.save();
        } catch (Exception e) {
            LOGGER.warn("[{}] Failed to auto-generate global config override file '{}' — continuing " +
                    "without one this load. Cause: {}", PhoenixDomains.MOD_ID, OVERRIDE_FILE_NAME, e.toString());
            return;
        } finally {
            fileConfig.close();
        }

        try {
            prependHeaderComment(overridePath);
        } catch (Exception e) {
            LOGGER.warn("[{}] Generated '{}' but failed to write its explanatory header comment — the " +
                    "file is still complete and usable. Cause: {}", PhoenixDomains.MOD_ID, OVERRIDE_FILE_NAME,
                    e.toString());
        }

        LOGGER.info("[{}] Generated global config override file '{}' with every key at its current default.",
                PhoenixDomains.MOD_ID, OVERRIDE_FILE_NAME);
    }

    /** Prepends a plain '#'-comment header to an already-saved override file. */
    private static void prependHeaderComment(Path overridePath) throws IOException {
        List<String> body = Files.readAllLines(overridePath);
        List<String> header = List.of(
                "# " + OVERRIDE_FILE_NAME,
                "#",
                "# Every value below is currently set to its shipped DEFAULT. This file is auto-generated the",
                "# first time it's missing, purely so it reads like a normal, complete config you can browse",
                "# and edit in place — not an empty stub you have to fill in from documentation.",
                "#",
                "# Editing a value here and saving is what makes it an ACTIVE override: on every subsequent",
                "# world/server load or config reload, any key whose value here differs from " +
                        PhoenixDomains.MOD_ID + "'s",
                "# current built-in default for that key is force-applied on top of that world's own",
                "# serverconfig. A key left untouched (still equal to the default) has no effect — that",
                "# world's own serverconfig (or the built-in default) applies normally.",
                "");
        List<String> combined = new ArrayList<>(header.size() + body.size());
        combined.addAll(header);
        combined.addAll(body);
        Files.write(overridePath, combined);
    }

    /** Reflects over {@link DomainsConfig}'s public static fields to find every declared config value. */
    private static Map<String, ForgeConfigSpec.ConfigValue<?>> collectConfigValues() throws IllegalAccessException {
        Map<String, ForgeConfigSpec.ConfigValue<?>> result = new HashMap<>();
        for (Field field : DomainsConfig.class.getDeclaredFields()) {
            if (!Modifier.isStatic(field.getModifiers()) || !Modifier.isPublic(field.getModifiers())) {
                continue;
            }
            if (!ForgeConfigSpec.ConfigValue.class.isAssignableFrom(field.getType())) {
                continue;
            }
            field.setAccessible(true);
            ForgeConfigSpec.ConfigValue<?> configValue = (ForgeConfigSpec.ConfigValue<?>) field.get(null);
            if (configValue == null) {
                continue;
            }
            List<String> path = configValue.getPath();
            result.put(String.join(".", path), configValue);
        }
        return result;
    }
}
